# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: false
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/cloud_lsp/all/cloud_lsp.rbi
#
# cloud_lsp-0.1.0

module RubyLsp
end
module RubyLsp::CloudLsp
end
class RubyLsp::CloudLsp::Addon < RubyLsp::Addon
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
