# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/logger/all/logger.rbi
#
# logger-1.6.6

class Logger
  include Logger::Severity
end
class Logger::Formatter
end
module Logger::Period
end
class Logger::LogDevice
  include Logger::Period
  include MonitorMixin
end
module Logger::Severity
end
class Logger::Error < RuntimeError
end
class Logger::ShiftingError < Logger::Error
end
