# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/rake/all/rake.rbi
#
# rake-13.2.1

module Rake
  extend Rake::FileUtilsExt
end
module Rake::Version
end
class Module
end
class String
end
module Rake::Win32
end
class Rake::Win32::Win32HomeError < RuntimeError
end
class Rake::LinkedList
  include Enumerable
end
class Rake::LinkedList::EmptyLinkedList < Rake::LinkedList
end
class Rake::CpuCounter
end
class Rake::Scope < Rake::LinkedList
end
class Rake::Scope::EmptyScope < Rake::LinkedList::EmptyLinkedList
end
class Rake::TaskArgumentError < ArgumentError
end
class Rake::RuleRecursionOverflowError < StandardError
end
module Rake::TaskManager
end
module Rake::Cloneable
end
module FileUtils
end
module Rake::FileUtilsExt
  extend Rake::FileUtilsExt
  include FileUtils
end
class Rake::FileList
  include Rake::Cloneable
end
class Rake::Promise
end
class Rake::ThreadPool
end
module Rake::PrivateReader
end
module Rake::PrivateReader::ClassMethods
end
class Rake::ThreadHistoryDisplay
  extend Rake::PrivateReader::ClassMethods
  include Rake::PrivateReader
end
module Rake::TraceOutput
end
class Rake::CommandLineOptionError < StandardError
end
class Rake::Application
  include Rake::TaskManager
  include Rake::TraceOutput
end
class Rake::PseudoStatus
end
class Rake::TaskArguments
  include Enumerable
end
class Rake::InvocationChain < Rake::LinkedList
end
class Rake::InvocationChain::EmptyInvocationChain < Rake::LinkedList::EmptyLinkedList
end
module Rake::InvocationExceptionMixin
end
class Rake::Task
end
class Rake::EarlyTime
  extend Singleton::SingletonClassMethods
  include Comparable
  include Singleton
end
class Rake::FileTask < Rake::Task
end
class Rake::FileCreationTask < Rake::FileTask
end
class Rake::MultiTask < Rake::Task
end
module Rake::DSL
  include Rake::FileUtilsExt
end
class Rake::DefaultLoader
end
class Rake::LateTime
  extend Singleton::SingletonClassMethods
  include Comparable
  include Singleton
end
class Rake::NameSpace
end
module Rake::Backtrace
end
