# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/rdoc/all/rdoc.rbi
#
# rdoc-6.12.0

module RDoc
end
class RDoc::I18n::Text
end
module RDoc::I18n
end
class RDoc::Error < RuntimeError
end
class RDoc::Options
end
