# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: false
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/ruby-lsp/all/ruby-lsp.rbi
#
# ruby-lsp-0.23.12

module RubyLsp
end
class RubyLsp::Addon
  extend T::Helpers
  extend T::Private::Abstract::Hooks
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
class RubyLsp::Addon::AddonNotFoundError < StandardError
end
class RubyLsp::Addon::IncompatibleApiError < StandardError
end
class RubyLsp::BaseServer
  extend T::Helpers
  extend T::Private::Abstract::Hooks
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
module URI
end
class URI::Generic
end
module RubyIndexer
end
class RubyIndexer::VisibilityScope
end
class RubyIndexer::DeclarationListener
end
class RubyIndexer::ReferenceFinder
end
class RubyIndexer::ReferenceFinder::Target
  extend T::Helpers
  extend T::Private::Abstract::Hooks
end
class RubyIndexer::ReferenceFinder::ConstTarget < RubyIndexer::ReferenceFinder::Target
end
class RubyIndexer::ReferenceFinder::MethodTarget < RubyIndexer::ReferenceFinder::Target
end
class RubyIndexer::ReferenceFinder::InstanceVariableTarget < RubyIndexer::ReferenceFinder::Target
end
class RubyIndexer::ReferenceFinder::Reference
end
class RubyIndexer::Enhancement
  extend T::Helpers
  extend T::Private::Abstract::Hooks
  extend T::Sig
end
class RubyIndexer::Index
end
class RubyIndexer::Index::UnresolvableAliasError < StandardError
end
class RubyIndexer::Index::NonExistingNamespaceError < StandardError
end
class RubyIndexer::Index::IndexNotEmptyError < StandardError
end
class RubyIndexer::Entry
end
class RubyIndexer::Entry::Visibility < T::Enum
end
class RubyIndexer::Entry::ModuleOperation
  extend T::Helpers
  extend T::Private::Abstract::Hooks
  extend T::Sig
end
class RubyIndexer::Entry::Include < RubyIndexer::Entry::ModuleOperation
end
class RubyIndexer::Entry::Prepend < RubyIndexer::Entry::ModuleOperation
end
class RubyIndexer::Entry::Namespace < RubyIndexer::Entry
  extend T::Helpers
  extend T::Private::Abstract::Hooks
  extend T::Sig
end
class RubyIndexer::Entry::Module < RubyIndexer::Entry::Namespace
end
class RubyIndexer::Entry::Class < RubyIndexer::Entry::Namespace
end
class RubyIndexer::Entry::SingletonClass < RubyIndexer::Entry::Class
end
class RubyIndexer::Entry::Constant < RubyIndexer::Entry
end
class RubyIndexer::Entry::Parameter
  extend T::Helpers
  extend T::Private::Abstract::Hooks
  extend T::Sig
end
class RubyIndexer::Entry::RequiredParameter < RubyIndexer::Entry::Parameter
end
class RubyIndexer::Entry::OptionalParameter < RubyIndexer::Entry::Parameter
end
class RubyIndexer::Entry::KeywordParameter < RubyIndexer::Entry::Parameter
end
class RubyIndexer::Entry::OptionalKeywordParameter < RubyIndexer::Entry::Parameter
end
class RubyIndexer::Entry::RestParameter < RubyIndexer::Entry::Parameter
end
class RubyIndexer::Entry::KeywordRestParameter < RubyIndexer::Entry::Parameter
end
class RubyIndexer::Entry::BlockParameter < RubyIndexer::Entry::Parameter
end
class RubyIndexer::Entry::ForwardingParameter < RubyIndexer::Entry::Parameter
end
class RubyIndexer::Entry::Member < RubyIndexer::Entry
  extend T::Helpers
  extend T::Private::Abstract::Hooks
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
class RubyIndexer::Entry::Accessor < RubyIndexer::Entry::Member
end
class RubyIndexer::Entry::Method < RubyIndexer::Entry::Member
end
class RubyIndexer::Entry::UnresolvedConstantAlias < RubyIndexer::Entry
end
class RubyIndexer::Entry::ConstantAlias < RubyIndexer::Entry
end
class RubyIndexer::Entry::GlobalVariable < RubyIndexer::Entry
end
class RubyIndexer::Entry::ClassVariable < RubyIndexer::Entry
end
class RubyIndexer::Entry::InstanceVariable < RubyIndexer::Entry
end
class RubyIndexer::Entry::UnresolvedMethodAlias < RubyIndexer::Entry
end
class RubyIndexer::Entry::MethodAlias < RubyIndexer::Entry
end
class RubyIndexer::Entry::Signature
end
class RubyIndexer::Configuration
end
class RubyIndexer::PrefixTree
  extend T::Generic
end
class RubyIndexer::PrefixTree::Node
  extend T::Generic
end
class RubyIndexer::Location
end
class RubyIndexer::RBSIndexer
end
class RubyLsp::DelegateRequestError < StandardError
end
class RubyLsp::Message
  extend T::Helpers
  extend T::Private::Abstract::Hooks
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
class RubyLsp::Notification < RubyLsp::Message
end
class RubyLsp::Request < RubyLsp::Message
end
class RubyLsp::Error
end
class RubyLsp::Result
end
class RubyLsp::RequestConfig
end
class RubyLsp::Scope
end
class RubyLsp::Scope::Local
end
class RubyLsp::ClientCapabilities
end
class RubyLsp::GlobalState
end
class RubyLsp::Server < RubyLsp::BaseServer
end
class RubyLsp::TypeInferrer
end
class RubyLsp::TypeInferrer::Type
end
class RubyLsp::TypeInferrer::GuessedType < RubyLsp::TypeInferrer::Type
end
class RubyLsp::NodeContext
end
class RubyLsp::Document
  extend T::Generic
  extend T::Helpers
  extend T::Private::Abstract::Hooks
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
class RubyLsp::Document::LanguageId < T::Enum
end
class RubyLsp::Document::LocationNotFoundError < StandardError
end
class RubyLsp::Document::Edit
  extend T::Helpers
  extend T::Private::Abstract::Hooks
  extend T::Sig
end
class RubyLsp::Document::Insert < RubyLsp::Document::Edit
end
class RubyLsp::Document::Replace < RubyLsp::Document::Edit
end
class RubyLsp::Document::Delete < RubyLsp::Document::Edit
end
class RubyLsp::Document::Scanner
  extend T::Sig
end
class RubyLsp::RubyDocument < RubyLsp::Document
  extend T::Generic
end
class RubyLsp::RubyDocument::SorbetLevel < T::Enum
end
class RubyLsp::ERBDocument < RubyLsp::Document
  extend T::Generic
end
class RubyLsp::ERBDocument::ERBScanner
end
class RubyLsp::RBSDocument < RubyLsp::Document
  extend T::Generic
end
class RubyLsp::Store
end
class RubyLsp::Store::NonExistingDocumentError < StandardError
end
module RubyLsp::ResponseBuilders
end
class RubyLsp::ResponseBuilders::ResponseBuilder
  extend T::Generic
  extend T::Private::Abstract::Hooks
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
class RubyLsp::ResponseBuilders::CollectionResponseBuilder < RubyLsp::ResponseBuilders::ResponseBuilder
  extend T::Generic
end
class RubyLsp::ResponseBuilders::DocumentSymbol < RubyLsp::ResponseBuilders::ResponseBuilder
end
class RubyLsp::ResponseBuilders::DocumentSymbol::SymbolHierarchyRoot
end
class RubyLsp::ResponseBuilders::Hover < RubyLsp::ResponseBuilders::ResponseBuilder
  extend T::Generic
end
class RubyLsp::ResponseBuilders::SemanticHighlighting < RubyLsp::ResponseBuilders::ResponseBuilder
end
class RubyLsp::ResponseBuilders::SemanticHighlighting::UndefinedTokenType < StandardError
end
class RubyLsp::ResponseBuilders::SemanticHighlighting::SemanticToken
end
class RubyLsp::ResponseBuilders::SemanticHighlighting::SemanticTokenEncoder
end
class RubyLsp::ResponseBuilders::SignatureHelp < RubyLsp::ResponseBuilders::ResponseBuilder
end
class RubyLsp::ResponseBuilders::TestCollection < RubyLsp::ResponseBuilders::ResponseBuilder
  extend T::Generic
end
module RubyLsp::Requests
end
module RubyLsp::Requests::Support
end
class RubyLsp::Requests::Support::SelectionRange < LanguageServer::Protocol::Interface::SelectionRange
end
class RubyLsp::Requests::Support::Annotation
end
class RubyLsp::Requests::Support::Sorbet
end
module RubyLsp::Requests::Support::Common
  extend T::Helpers
end
module RubyLsp::Requests::Support::Formatter
  extend T::Helpers
  extend T::Private::Abstract::Hooks
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
class RubyLsp::Requests::Support::TestItem
end
class RubyLsp::Requests::Request
  extend T::Generic
  extend T::Private::Abstract::Hooks
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
class RubyLsp::Requests::Request::InvalidFormatter < StandardError
end
class RubyLsp::Requests::CodeActionResolve < RubyLsp::Requests::Request
  include RubyLsp::Requests::Support::Common
end
class RubyLsp::Requests::CodeActionResolve::CodeActionError < StandardError
end
class RubyLsp::Requests::CodeActionResolve::Error < T::Enum
end
class RubyLsp::Requests::CodeActions < RubyLsp::Requests::Request
end
module RubyLsp::Listeners
end
class RubyLsp::Listeners::CodeLens
  include RubyLsp::Requests::Support::Common
end
class RubyLsp::Requests::CodeLens < RubyLsp::Requests::Request
end
class RubyLsp::Requests::CompletionResolve < RubyLsp::Requests::Request
  include RubyLsp::Requests::Support::Common
end
class RubyLsp::Listeners::Completion
  include RubyLsp::Requests::Support::Common
end
class RubyLsp::Requests::Completion < RubyLsp::Requests::Request
end
class RubyLsp::Listeners::Definition
  include RubyLsp::Requests::Support::Common
end
class RubyLsp::Requests::Definition < RubyLsp::Requests::Request
  extend T::Generic
end
class RubyLsp::Requests::Diagnostics < RubyLsp::Requests::Request
end
class RubyLsp::Listeners::TestStyle
  include RubyLsp::Requests::Support::Common
end
class RubyLsp::Listeners::SpecStyle
  extend T::Sig
  include RubyLsp::Requests::Support::Common
end
class RubyLsp::Requests::DiscoverTests < RubyLsp::Requests::Request
  include RubyLsp::Requests::Support::Common
end
class RubyLsp::Listeners::DocumentHighlight
  include RubyLsp::Requests::Support::Common
end
class RubyLsp::Requests::DocumentHighlight < RubyLsp::Requests::Request
end
class URI::Source < URI::File
end
class RubyLsp::Listeners::DocumentLink
  include RubyLsp::Requests::Support::Common
end
class RubyLsp::Requests::DocumentLink < RubyLsp::Requests::Request
end
class RubyLsp::Listeners::DocumentSymbol
  include RubyLsp::Requests::Support::Common
end
class RubyLsp::Requests::DocumentSymbol < RubyLsp::Requests::Request
end
class RubyLsp::Listeners::FoldingRanges
  include RubyLsp::Requests::Support::Common
end
class RubyLsp::Requests::FoldingRanges < RubyLsp::Requests::Request
end
class RubyLsp::Requests::Formatting < RubyLsp::Requests::Request
end
class RubyLsp::Requests::Formatting::Error < StandardError
end
class RubyLsp::Requests::GoToRelevantFile < RubyLsp::Requests::Request
  extend T::Sig
end
class RubyLsp::Listeners::Hover
  include RubyLsp::Requests::Support::Common
end
class RubyLsp::Requests::Hover < RubyLsp::Requests::Request
  extend T::Generic
end
class RubyLsp::Listeners::InlayHints
  include RubyLsp::Requests::Support::Common
end
class RubyLsp::Requests::InlayHints < RubyLsp::Requests::Request
end
class RubyLsp::Requests::OnTypeFormatting < RubyLsp::Requests::Request
end
class RubyLsp::Requests::PrepareTypeHierarchy < RubyLsp::Requests::Request
  include RubyLsp::Requests::Support::Common
end
class RubyLsp::Requests::PrepareRename < RubyLsp::Requests::Request
  include RubyLsp::Requests::Support::Common
end
class RubyLsp::Requests::RangeFormatting < RubyLsp::Requests::Request
end
class RubyLsp::Requests::References < RubyLsp::Requests::Request
  include RubyLsp::Requests::Support::Common
end
class RubyLsp::Requests::Rename < RubyLsp::Requests::Request
  include RubyLsp::Requests::Support::Common
end
class RubyLsp::Requests::Rename::InvalidNameError < StandardError
end
class RubyLsp::Requests::SelectionRanges < RubyLsp::Requests::Request
  include RubyLsp::Requests::Support::Common
end
class RubyLsp::Listeners::SemanticHighlighting
  include RubyLsp::Requests::Support::Common
end
class RubyLsp::Requests::SemanticHighlighting < RubyLsp::Requests::Request
end
class RubyLsp::Requests::ShowSyntaxTree < RubyLsp::Requests::Request
end
class RubyLsp::Listeners::SignatureHelp
  include RubyLsp::Requests::Support::Common
end
class RubyLsp::Requests::SignatureHelp < RubyLsp::Requests::Request
end
class RubyLsp::Requests::TypeHierarchySupertypes < RubyLsp::Requests::Request
  include RubyLsp::Requests::Support::Common
end
class RubyLsp::Requests::WorkspaceSymbol < RubyLsp::Requests::Request
  include RubyLsp::Requests::Support::Common
end
