# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/yard/all/yard.rbi
#
# yard-0.9.37

module YARD
end
module YARD::Server
end
module YARD::CLI
end
module YARD::CodeObjects
end
module YARD::Handlers
end
module YARD::Handlers::Common
end
module YARD::Handlers::C
end
module YARD::Handlers::Ruby
end
module YARD::Handlers::Ruby::Legacy
end
module YARD::I18n
end
module YARD::Parser
end
module YARD::Parser::C
end
module YARD::Parser::Ruby
end
module YARD::Parser::Ruby::Legacy
end
module YARD::Rake
end
module YARD::Serializers
end
module YARD::Server::Commands
end
module YARD::Tags
end
module YARD::Templates
end
module YARD::Templates::Helpers
end
module YARD::Templates::Helpers::Markup
end
class YARD::Config
end
class Array
end
class File < IO
end
class Insertion
end
class Module
end
class String
end
class SymbolHash < Hash
end
module Gem
end
class Gem::SourceIndex
  include Enumerable
end
class YARD::Options
end
class YARD::Templates::TemplateOptions < YARD::Options
end
class YARD::CLI::Command
end
class YARD::CLI::YardoptsCommand < YARD::CLI::Command
end
class YARD::CLI::YardocOptions < YARD::Templates::TemplateOptions
end
class YARD::CLI::Yardoc < YARD::CLI::YardoptsCommand
end
